export default {
  getCardsEndpoint: "http://localhost:8000/service/getCards.php",
  getCardTokenSecureEndpoint: "https://omccstb.turkcell.com.tr/paymentmanagement/rest/getCardTokenSecure",
  generateHashDataEndpoint: "http://localhost:8000/service/generateHashData.php",
  registerCardEndpoint: "http://localhost:8000/service/registerCard.php",
  deleteCardEndpoint: "http://localhost:8000/service/deleteCard.php",
  updateCardEndpoint: "http://localhost:8000/service/updateCard.php",
  getThreeDSessionEndpoint: "http://localhost:8000/service/getThreeDSession.php",
  getThreeDSessionResultEndpoint: "http://localhost:8000/service/getThreeDSessionResult.php",
  getTermsOfServiceEndpoint: "http://localhost:8000/service/getTermsOfServiceContent.php",
  getPaymentMethodsEndpoint: "http://localhost:8000/service/getPaymentMethods.php",
  provisionEndpoint: "http://localhost:8000/service/provision.php",
  provisionAllEndpoint: "http://localhost:8000/service/provisionAll.php",
  provisionForMarketPlaceEndpoint: "http://localhost:8000/service/provisionForMarketPlace.php",
  getProvisionHistoryEndpoint: "http://localhost:8000/service/getProvisionHistory.php",
  inquireEndpoint: "http://localhost:8000/service/inquire.php",
  inquireAllEndpoint: "http://localhost:8000/service/inquireAll.php",
  reverseEndpoint: "http://localhost:8000/service/reverse.php",
  refundEndpoint: "http://localhost:8000/service/refund.php",
  refundAllEndpoint: "http://localhost:8000/service/refundAll.php",
  summaryReconciliationEndpoint: "http://localhost:8000/service/summaryReconciliation.php",
  sendOtpEndpoint: "http://localhost:8000/service/sendOtp.php",
  validateOtpEndpoint: "http://localhost:8000/service/validateOtp.php",
  openMobilePaymentEndpoint: "http://localhost:8000/service/openMobilePayment.php",
}