export interface SummaryReconciliationState {
  reconciliationDate?: String,
  reconciliationResult?: String,
  totalPostAuthAmount?: String,
  totalPostAuthCount?: Number,
  totalPostAuthReverseAmount?: String,
  totalPostAuthReverseCount?: Number,
  totalPreAuthAmount?: String,
  totalPreAuthCount?: Number,
  totalPreAuthReverseAmount?: String,
  totalPreAuthReverseCount?: Number,
  totalRefundAmount?: String,
  totalRefundCount?: Number,
  totalReverseAmount?: String,
  totalReverseCount?: Number,
  totalSaleAmount?: String,
  totalSaleCount?: Number,
}